name = "Collatz"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Collatz"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.unusedVariables = true
weak.linter.style.longLine = false
weak.linter.unusedSectionVars = true
weak.linter.style.emptyLine = true
weak.linter.style.nativeDecide = true
weak.linter.unusedSimpArgs = true
weak.linter.style.commandStart = true
weak.linter.unnecessarySimpa = true
weak.linter.unusedTactic = true
weak.linter.style.show = true


[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "v4.26.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "Collatz"
